defmodule AshAi.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add(:created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))
      add(:updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))
    end
  end

  def down do
    alter table(:artists) do
      remove(:updated_at)
      remove(:created_at)
    end
  end
end
