defmodule AshAi.TestRepo.Migrations.AllowForMultipleFullTextVectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add(:name_full_text_vector, :vector, size: 1536)
    end
  end

  def down do
    alter table(:artists) do
      remove(:name_full_text_vector)
    end
  end
end
