defmodule AshAi.TestRepo.Migrations.AddGroupByTestColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add(:label, :text)
      add(:play_count, :bigint)
    end
  end

  def down do
    alter table(:artists) do
      remove(:play_count)
      remove(:label)
    end
  end
end
